#!/usr/bin/env bash

# -----------------------------------------------------------------
# Programmable completion specification for conntrackd (netfilter)
# http://www.netfilter.org/projects/conntrack/index.html
#
# Project home:
# https://github.com/AllKind/conntrack-tools-bash_completion
# http://sourceforge.net/p/conntrack-tools-bash-compl
# -----------------------------------------------------------------

# Copyright (C) 2016 Mart Frauenlob aka AllKind (AllKind@fastest.cc)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# -----------------------------------------------------------------
# Requirements:
#
# The bash completion package version 2.0 or greater is recommended.
# https://github.com/scop/bash-completion
# If bash completion is present, and the version includes the
# `_init_completion()' function, completion on variables and redirection
# is available in addition. Otherwise only option completion is fully supported.
# -----------------------------------------------------------------

# -----------------------------------------------------------------
# Installation (quote from bash-completion README):
#
# Install it in one of the directories pointed to by
# bash-completion's pkgconfig file variables.  There are two
# alternatives: the recommended one is 'completionsdir' (get it with
# "pkg-config --variable=completionsdir bash-completion") from which
# completions are loaded on demand based on invoked commands' names,
# so be sure to name your completion file accordingly, and to include
# for example symbolic links in case the file provides completions
# for more than one command.  The other one which is present for
# backwards compatibility reasons is 'compatdir' (get it with
# "pkg-config --variable=compatdir bash-completion") from which files
# are loaded when bash_completion is loaded.
#
# For packages using GNU autotools the installation can be handled
# for example like this in configure.ac:
#
#  PKG_CHECK_VAR(bashcompdir, [bash-completion], [completionsdir], ,
#    bashcompdir="${sysconfdir}/bash_completion.d")
#  AC_SUBST(bashcompdir)
#
# ...accompanied by this in Makefile.am:
#
#  bashcompdir = @bashcompdir@
#  dist_bashcomp_DATA = # completion files go here
#
# For cmake we ship the bash-completion-config.cmake and
# bash-completion-config-version.cmake files. Example usage:
#
#  find_package(bash-completion)
#  if(BASH_COMPLETION_FOUND)
#    message(STATUS
#      "Using bash completion dir ${BASH_COMPLETION_COMPLETIONSDIR}")
#  else()
#    set (BASH_COMPLETION_COMPLETIONSDIR "/etc/bash_completion.d")
#    message (STATUS
#      "Using fallback bash completion dir ${BASH_COMPLETION_COMPLETIONSDIR}")
#  endif()
#
#  install(FILES your-completion-file DESTINATION
#    ${BASH_COMPLETION_COMPLETIONSDIR})
#
# For backwards compatibility it is still possible to put it into
# ~/.bash_completion or /etc/bash_completion.d/.
# -----------------------------------------------------------------
#
# Version 1.0
#
# -----------------------------------------------------------------

shopt -s extglob

_conntrackd_complete() {
local cur prev cword words
local -i i

COMPREPLY=()

# if _init_completion() from bash_completion is available, use it to deal with
# variables and redirections. otherwise use _get_comp_words_by_ref().
# as fallback we commpose our own variables.
if declare -f _init_completion &>/dev/null; then
	_init_completion || return # ret val -gt 0 = nothing more to do
elif declare -f _get_comp_words_by_ref &>/dev/null; then
    _get_comp_words_by_ref cur prev cword words || return
else # not so neat, but a workaround
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cword=$COMP_CWORD
    for i in ${!COMP_WORDS[@]}; do words[i]="${COMP_WORDS[i]}"; done
fi

if ((cword == 1)); then # main command
	COMPREPLY=($(compgen -W '-d -i -e -x -f -F -c -B -n -k -s -R -t -v -h -C' -- "$cur"))
elif ((cword >= 2)); then
	if [[ $cur = -* ]]; then # option request
		if [[ ${words[1]} = @(-d|-h|-v) ]]; then
			return 0
		fi
		COMPREPLY=($(compgen -W '-i -e -x -f -F -c -B -n -k -s -R -t -C' -- "$cur"))
	else # non option request
		if [[ $prev = @(-i|-e|-F|-R) ]]; then
			COMPREPLY=( $(compgen -W 'ct expect' -- "$cur") )
		elif [[ $prev = -f ]]; then
			COMPREPLY=( $(compgen -W 'internal external' -- "$cur") )
		elif [[ $prev = -s ]]; then
			COMPREPLY=( $(compgen -W \
				'network cache runtime link rsqueue process queue ct expect' -- "$cur") )
		elif [[ $prev = -C ]]; then
			if declare -p _filedir &>/dev/null; then
				_filedir # use bash completion function if available
			else
				compopt -o nospace
				COMPREPLY=( $( compgen -f -- "$cur" ) )
			fi
		fi
	fi
fi
}

complete -F _conntrackd_complete conntrackd

